# Generated by Django 2.2.3 on 2020-10-02 15:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mision',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='business',
            name='vision',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Vision'),
        ),
    ]
