# Generated by Django 2.2.3 on 2020-10-07 15:45

import ckeditor_uploader.fields
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201002_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='telefono',
        ),
        migrations.AddField(
            model_name='business',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='telefonos',
            field=models.CharField(default=1, max_length=50, validators=[core.validators.validate_only_numbers, django.core.validators.MinLengthValidator(5)], verbose_name='Telefonos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='wpp',
            field=models.CharField(default=1, max_length=50, validators=[core.validators.validate_only_numbers, django.core.validators.MinLengthValidator(5)], verbose_name='Whatsapp'),
            preserve_default=False,
        ),
    ]
