# Generated by Django 2.2.3 on 2020-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20200930_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Retapizado'), (2, 'Fabricacion'), (3, 'Restauracion')], default=1, verbose_name='Categoria'),
        ),
    ]
