# Generated by Django 2.2.3 on 2020-10-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_auto_20201002_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['-creacion'], 'verbose_name': 'Trabajos', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
