# Generated by Django 2.2.3 on 2020-10-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Telas'), (2, 'Maderas'), (3, 'Pinturas')], default=1, verbose_name='Categoria'),
        ),
    ]
