# Generated by Django 2.2.3 on 2020-10-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_auto_20201007_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-creacion'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
