# Generated by Django 2.2.3 on 2020-11-03 15:05

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, validators=[core.validators.validate_only_letters, django.core.validators.MinLengthValidator(3)], verbose_name='Titulo'),
        ),
    ]
